"""first migrations

Revision ID: 25ba5128e55f
Revises: 
Create Date: 2026-03-11 11:07:44.039805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ba5128e55f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('calls_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['user_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('from_number', sa.String(length=25), nullable=True),
    sa.Column('to_number', sa.String(length=25), nullable=True),
    sa.Column('call_type', sa.Enum('INB', 'OUT', name='calltype'), nullable=True),
    sa.Column('call_state', sa.Enum('ANSWER', 'NOANSWER', 'BUSY', 'FAILED', name='callstate'), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('seconds_fulltime', sa.Float(), nullable=True),
    sa.Column('seconds_talktime', sa.Float(), nullable=True),
    sa.Column('mp3_link', sa.String(length=255), nullable=True),
    sa.Column('callback', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_type_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['user_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('call_ai_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('attention_to_the_call', sa.String(length=255), nullable=True),
    sa.Column('operator_errors', sa.String(length=255), nullable=True),
    sa.Column('next_steps', sa.String(length=255), nullable=True),
    sa.Column('key_points_of_the_dialogue', sa.String(length=255), nullable=True),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.Column('clients_mood', sa.String(length=255), nullable=True),
    sa.Column('operators_mood', sa.String(length=255), nullable=True),
    sa.Column('badwords', sa.String(length=255), nullable=True),
    sa.Column('foul_language', sa.String(length=255), nullable=True),
    sa.Column('conversation_topic', sa.String(length=255), nullable=True),
    sa.Column('customer_satisfaction', sa.String(length=255), nullable=True),
    sa.Column('problem_solving_efficiency', sa.String(length=255), nullable=True),
    sa.Column('ability_to_adapt', sa.String(length=255), nullable=True),
    sa.Column('involvement', sa.String(length=255), nullable=True),
    sa.Column('problem_identification', sa.String(length=255), nullable=True),
    sa.Column('clarity_of_communication', sa.String(length=255), nullable=True),
    sa.Column('empathy', sa.String(length=255), nullable=True),
    sa.Column('operator_professionalism', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_ai_analytics')
    op.drop_table('user_type_association')
    op.drop_table('calls')
    op.drop_table('users')
    op.drop_table('user_types')
    op.drop_table('user_categories')
    # ### end Alembic commands ###
