"""third migrations

Revision ID: a537cfeafdd4
Revises: 5b5389093654
Create Date: 2026-03-12 15:37:39.737827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a537cfeafdd4'
down_revision: Union[str, Sequence[str], None] = '5b5389093654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_category_id_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_category_id_key'), 'users', ['category_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
